name: Openwrt-build

on: push

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run Shell Script
      run: ./test.sh
    
      #    - name: Upload artifact
      #      uses: actions/upload-artifact@master
      #      with:
      #  name: testfile
  #  path: ./output
